#!/bin/bash

if ! command -v twint &> /dev/null; then
    echo "twint is not installed. Installing..."
    pip3 install --user --upgrade git+https://github.com/Agencia-Scrum/twint.git
fi

twint -fr -u $1 -o $1.csv --csv
